apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-04
  namespace: api-monetization-apps
spec:
  selector:
    matchLabels: {app.kubernetes.io/name: 'demo-app-04'}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

