apiVersion: v1
kind: Service
metadata:
  name: demo-app-04
  namespace: api-monetization-apps
  labels: {app.kubernetes.io/name: 'demo-app-04'}
spec:
  selector: {app.kubernetes.io/name: 'demo-app-04'}
  ports:
    - {name: http, port: 8080, targetPort: http}
    - {name: http-openapi, port: 8082, targetPort: openapi}
